# Generated by Django 5.2.4 on 2025-07-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin', models.CharField(max_length=50, verbose_name='Fin')),
                ('sea', models.BooleanField(default=False, verbose_name='Sea')),
                ('tmg', models.BooleanField(default=False, verbose_name='TMG')),
                ('efis', models.BooleanField(default=False, verbose_name='Efis')),
                ('fnpt', models.IntegerField(default=0, verbose_name='FNPT')),
                ('make', models.CharField(max_length=50, verbose_name='Make')),
                ('run2', models.BooleanField(default=False, verbose_name='Run2')),
                ('_class', models.IntegerField(default=0, verbose_name='Class')),
                ('model', models.CharField(max_length=50, verbose_name='Model')),
                ('power', models.IntegerField(default=0, verbose_name='Power')),
                ('seats', models.IntegerField(default=0, verbose_name='Seats')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('kg5700', models.BooleanField(default=False, verbose_name='Kg5700')),
                ('rating', models.CharField(max_length=50, verbose_name='Rating')),
                ('company', models.CharField(max_length=50, verbose_name='Company')),
                ('_complex', models.BooleanField(default=False, verbose_name='Complex')),
                ('cond_log', models.IntegerField(default=0, verbose_name='CondLog')),
                ('fav_list', models.BooleanField(default=False, verbose_name='FavList')),
                ('category', models.IntegerField(default=0, verbose_name='Category')),
                ('high_perf', models.BooleanField(default=False, verbose_name='HighPerf')),
                ('sub_model', models.CharField(max_length=50, verbose_name='SubModel')),
                ('aerobatic', models.BooleanField(default=False, verbose_name='Aerobatic')),
                ('ref_search', models.CharField(max_length=50, verbose_name='RefSearch')),
                ('reference', models.CharField(max_length=50, verbose_name='Reference')),
                ('tailwheel', models.BooleanField(default=False, verbose_name='Tailwheel')),
                ('default_app', models.IntegerField(default=0, verbose_name='DefaultApp')),
                ('default_log', models.IntegerField(default=0, verbose_name='DefaultLog')),
                ('default_ops', models.IntegerField(default=0, verbose_name='DefaultOps')),
                ('device_code', models.IntegerField(default=0, verbose_name='DeviceCode')),
                ('aircraft_code', models.CharField(max_length=50, verbose_name='AircraftCode')),
                ('default_launch', models.IntegerField(default=0, verbose_name='DefaultLaunch')),
                ('record_modified', models.IntegerField(default=0, verbose_name='Record_Modified')),
            ],
        ),
    ]
