# Generated by Django 5.2.4 on 2025-07-25 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilotlog', '0002_remove_aircraft_id_alter_aircraft_aircraft_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='aircraft_code',
            field=models.ForeignKey(db_column='aircraft_code', on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='pilotlog.aircraft', verbose_name='AircraftCode'),
        ),
    ]
